/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 7.0.2 */
package analyzer.ast;

public interface ParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTASSIGNSTMT = 2;
  public int JJTIDENTIFIER = 3;
  public int JJTINTVALUE = 4;
  public int JJTREALVALUE = 5;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "AssignStmt",
    "Identifier",
    "IntValue",
    "RealValue",
  };
}
/* JavaCC - OriginalChecksum=9dc885d4c28b6ce0f11c301209bc9b4f (do not edit this line) */
